# Generated by Django 5.2 on 2025-05-08 17:36

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='logos/')),
                ('fabicon', models.ImageField(upload_to='favicons/')),
                ('address', models.TextField()),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email')),
                ('website', models.URLField(blank=True, null=True, unique=True, verbose_name='Website')),
                ('facebook', models.URLField(blank=True, null=True, unique=True, verbose_name='Facebook')),
                ('youtube', models.URLField(blank=True, null=True, unique=True, verbose_name='Youtube')),
            ],
        ),
    ]
